extended graphics object to calculats 1d potentials. (at this point pseudo only)

diff --git a/src/Tools/Scripts/paw_get b/src/Tools/Scripts/paw_get
--- a/src/Tools/Scripts/paw_get
+++ b/src/Tools/Scripts/paw_get
@@ -27,6 +27,7 @@ USAGE="$USAGE \t\t whatid=volume \t prints volume of the unit cell \n"
 USAGE="$USAGE \t\t whatid=epw    \t prints wavefunction plane wave cutoff \n"
 USAGE="$USAGE \t\t whatid=epwrho \t prints density plane wave cutoff \n"
 USAGE="$USAGE \t\t whatid=nkpt   \t prints the number of k-points\n"
+USAGE="$USAGE \t\t whatid=kdiv   \t prints the divisions for the k-grid\n"
 USAGE="$USAGE \t -n prints the result as number or according to -u\n"
 USAGE="$USAGE \t -t prints the result as text (default)\n"
 USAGE="$USAGE \t -u unit: 1|ev|kj/mol|kcal/mol|h|ry|angstrom^3|aa^3|cubangstrom|a0^3|abohr^3|cubabohr \n"
@@ -36,6 +37,16 @@ USAGE="$USAGE \t -h prints this help message\n"
 #  implement dry-run
 #-------------------------------------------------------------------------------
 function execute(){
+    if [[ "$DRYRUN" != yes && "$DRYRUN" != 'no' ]] ; then
+      echo "error in $0: illegal value '$DRYRUN' of DRYRUN"
+      echo "DRYRUN must be either 'yes' or 'no'"
+      exit 1
+    fi
+    if [[ "$VERBOSE" != yes && "$VERBOSE" != 'no' ]] ; then
+      echo "error in $0: illegal value '$VERBOSE' of VERBOSE"
+      echo "VERBOSE must be either 'yes' or 'no'"
+      exit 1
+    fi
     # || is "or" in [[...]], && is "and" in [[..]]
     if [[ "${DRYRUN}" = "yes" || "${VERBOSE}" = "yes" ]] ; then
       echo "${@}"
@@ -138,7 +149,7 @@ while getopts :hw:tnp:vu: OPT ; do
   case $OPT in 
     w) WHATID="$OPTARG" 
        case $WHATID in
-         etot|gap|homo|lumo|efermi|volume|nkpt|epw|epwrho) 
+         etot|gap|homo|lumo|efermi|volume|nkpt|kdiv|epw|epwrho) 
          ;; 
          *)
            echo "error in $0: illegal argument $WHATID of option -w" >&2
@@ -207,6 +218,7 @@ fi
 if [[ -z $UNIT ]] ; then
   case $WHATID in 
     nkpt) ;;
+    kdiv) ;;
     *) echo error: missing argument -u. specify UNIT  >&2 ; exit 1 ;;
   esac
 fi
@@ -242,7 +254,7 @@ case $WHATID in
         ;;
     esac
     ;;
-  nkpt)
+  nkpt|kdiv)
     if [[ -n $UNIT ]] ; then
       echo "error in $0: unit inconsistency" >&2
       echo "volume variable $WHATID inconsistent with unit $UNIT" >&2
@@ -335,6 +347,15 @@ elif [[ "$WHATID" = "nkpt" ]] ; then
   export WHAT="NUMBER OF K-POINTS" 
   export RESULT=$(grep "$WHAT" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
 #
+#--------------  nkpt  ---------------------------------------------------------
+#
+elif [[ "$WHATID" = "kdiv" ]] ; then
+  export WHAT="DIVISIONS FOR K-GRID" 
+  export NK1=$(grep "$kdiv(1)" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+  export NK2=$(grep "$kdiv(2)" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+  export NK3=$(grep "$kdiv(3)" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+  export RESULT="${NK1} ${NK2} ${NK3}"
+#
 #--------------  EPW(psi)-------------------------------------------------------
 #
 elif [[ "$WHATID" = "epw" ]] ; then
@@ -361,7 +382,7 @@ fi
 #  convert units
 ################################################################################
 case $WHATID in
- nkpt) ;;                                 # no unit 
+ nkpt|kdiv) ;;                            # no unit 
  *) RESULT=$(convertunit $UNIT "$RESULT") # internal function convertunit 
    ;;
 esac
@@ -370,7 +391,10 @@ esac
 #  switch between number and text output and edit result
 ################################################################################
 if [[ $TN = N ]] ; then 
-  RESULT=$(echo "$RESULT" | awk '{print $1}')
+  case $WHATID in
+    kdiv) ;;
+    *) RESULT=$(echo "$RESULT" | awk '{print $1}') ;;
+  esac
 else
   RESULT=$(echo "$WHATID = $RESULT for $ROOT")
 fi
diff --git a/src/Tools/Scripts/paw_scan b/src/Tools/Scripts/paw_scan
--- a/src/Tools/Scripts/paw_scan
+++ b/src/Tools/Scripts/paw_scan
@@ -120,6 +120,16 @@ export VERBOSE=no
 #  implement dry-run
 #-------------------------------------------------------------------------------
 function execute(){
+    if [[ "$DRYRUN" != yes && "$DRYRUN" != 'no' ]] ; then
+      echo "error in $0: illegal value '$DRYRUN' of DRYRUN"
+      echo "DRYRUN must be either 'yes' or 'no'"
+      exit 1
+    fi
+    if [[ "$VERBOSE" != yes && "$VERBOSE" != 'no' ]] ; then
+      echo "error in $0: illegal value '$VERBOSE' of VERBOSE"
+      echo "VERBOSE must be either 'yes' or 'no'"
+      exit 1
+    fi
     # || is "or" in [[...]], && is "and" in [[..]] 
     if [[ "${DRYRUN}" = "yes" || "${VERBOSE}" = "yes" ]] ; then
       echo "${@}"
diff --git a/src/Tools/Scripts/paw_scanlat b/src/Tools/Scripts/paw_scanlat
--- a/src/Tools/Scripts/paw_scanlat
+++ b/src/Tools/Scripts/paw_scanlat
@@ -34,6 +34,11 @@
 #  this occurrance will be replaced by the varied values for the 
 #  individual runs.
 #
+#  specify k-points in the structure file with !STRUCTURE!KPOINTS:DIV=
+#  rather than using R=. Otherwise the k-point grid changes between 
+#  different values of lattice constant and the restart file becomes 
+#  unusable.
+#
 #  result       etot.dat 
 #               gap.dat
 #               murn.in
@@ -79,12 +84,25 @@ export PAWXDIR=$(which paw_fast.x); PAWXDIR=${PAWXDIR%paw_fast.x}
 #  implement dry-run
 #-------------------------------------------------------------------------------
 function execute(){
+    if [[ "$DRYRUN" != yes && "$DRYRUN" != 'no' ]] ; then
+      echo "error in $0" >&2
+      echo "illegal value '$DRYRUN' of DRYRUN" >&2
+      echo "DRYRUN must be either 'yes' or 'no'" >&2
+      exit 1
+    fi
+    if [[ "$VERBOSE" != yes && "$VERBOSE" != 'no' ]] ; then
+      echo "error in $0" >&2
+      echo "illegal value '$VERBOSE' of VERBOSE" >&2
+      echo "VERBOSE must be either 'yes' or 'no'" >&2
+      exit 1
+    fi
     # || is "or" in [[...]], && is "and" in [[..]] 
     if [[ "${DRYRUN}" = "yes" || "${VERBOSE}" = "yes" ]] ; then
       echo "${@}"
     fi
     if [[ "${DRYRUN}" = "no" ]] ; then
       eval "$@"
+      export PID=$!
     fi
 }
    #
@@ -145,7 +163,7 @@ fi
 #
 # when PAWCMD has not been defined via arguments, set default
 if [[ -z $PAWCMD ]] ; then
-  PAWCMD="paw_waittllempty -n $NJOBS ; paw_fast"
+  PAWCMD="paw_waittillempty -n $NJOBS ; paw_fast"
 fi
 #
 #   report setting of variables
@@ -178,6 +196,7 @@ ALAT0=$X
 # loop crystal calculation through different lattic constants                ==
 #==============================================================================
 if [[ $UPDATE = no ]] ; then
+  export PIDS=
   for X in $ALATLIST; do
     if [[ $VERBOSE = yes ]] ; then echo doing $X ; fi 
     #===========================================================================
@@ -192,6 +211,9 @@ if [[ $UPDATE = no ]] ; then
     if [[ ! -e ${NAME}_${X}.rstrt ]] ; then
       if [[ -e ${NAME}.rstrt ]] ; then
         execute "cp ${NAME}.rstrt ${NAME}_${X}.rstrt"
+      else
+        echo "error in $0: source restart file ${NAME}.rstrt does not exist"
+        exit 1
       fi
     fi
     export ROOT=${NAME}_${X}
@@ -200,10 +222,23 @@ if [[ $UPDATE = no ]] ; then
     BACK=$(pwd)
     execute "cd ${PDIR}"
     execute "${PAWCMD} ${NAME}_${X}.cntl 1>${NAME}_${X}.out 2>&1 &" 
+    PIDS="$PIDS $PID"   # store the project id returned by 'execute'
     execute "cd ${BACK}"
   done
 fi
-
+#
+#============================================================================
+#==  wait until all submitted jobs ($PIDS) are finished
+#============================================================================
+export NACTIVE=1
+while [ ${NACTIVE} -gt 0 ] ; do
+  echo No.Jobs=$NACTIVE Date=`date` waiting....
+  sleep  1s
+  NACTIVE=0
+  for X in ${PIDS} ; do
+    if [[ -n  $(ps -p $X -o pid= ) ]] ; then  NACTIVE=$(( $NACTIVE + 1 )); fi
+  done
+done
 #
 #==============================================================================
 # update data files
@@ -214,7 +249,7 @@ if [[ $UPDATE = yes ]] ; then
   if [[ -e murn.in ]]  ; then rm murn.in; fi
   for X in $ALATLIST; do
     if [[ $VERBOSE = yes ]] ; then echo "collecting ${NAME}_$X" ; fi
-    echo ${X} $(paw_get -w gap -u ev -n ${NAME}_${X})  >>gap.dat
+#    echo ${X} $(paw_get -w gap -u ev -n ${NAME}_${X})  >>gap.dat
     echo ${X} $(paw_get -w etot -u H -n ${NAME}_${X}) >>etot.dat
     ALAT=$(echo "$X /100 * $ALAT0 " | bc -l)
     Y=$(echo "$ALAT * $AA" | bc -l)
