bugfix in tool paw_do

diff --git a/src/Tools/Scripts/paw_do b/src/Tools/Scripts/paw_do
--- a/src/Tools/Scripts/paw_do
+++ b/src/Tools/Scripts/paw_do
@@ -14,7 +14,10 @@
 #          -f    execute paw_fast.x
 #          -d    execute paw_dos.x and paw_dosplot.x
 #          -s    execute paw_strc.x
-#          -w    execute paw_show -ce
+#          -w    execute paw_wave.x
+#          -t    execute paw_tra.x
+#          -a    execute paw_show -ce
+#          -z    execute tail -f ROOT.prot
 #          -0:   dry-run
 #          -b:   directory containing the paw executables
 #          -v:   verbose
@@ -24,6 +27,9 @@
 #
 #   REQUIREMENTS: 
 #                  paw_dos.x,paw_dosplot.x,paw_show,paw_fast,paw_strc.x
+#                  paw_wave.x,paw_tra.x
+#          the scripts rely on the fact that exactly one file with the
+#          required extension lies in the local directory.
 #
 #         AUTHOR: Peter E. Bloechl; peter.bloechl@tu-clausthal.de
 #
@@ -42,10 +48,14 @@ USAGE="$USAGE \t frontend for paw code and tools"
 USAGE="$USAGE \n"
 USAGE="$USAGE Options:\n"
 USAGE="$USAGE \t -h \t print this help message \n"
-USAGE="$USAGE \t -f: paw_fast.x 1>out 2>&1 & \n"
-USAGE="$USAGE \t -d: paw_dos.x ; paw_dosplot.x; xmgrace \n"
-USAGE="$USAGE \t -s: paw_strc.x -c \n"
-USAGE="$USAGE \t -w: paw_show -ce \n"
+USAGE="$USAGE \t -a: paw_show -ce ROOT\n"
+USAGE="$USAGE \t -f: paw_fast.x ROOT.cntl 1>out 2>&1 & \n"
+USAGE="$USAGE \t -d: paw_dos.x ROOT.dcntl \n"
+USAGE="$USAGE \t\t   paw_dosplot.x ROOT.dpcntl; xmgrace -batch ROOT.bat\n"
+USAGE="$USAGE \t -s: paw_strc.x -c ROOT\n"
+USAGE="$USAGE \t -t: paw_tra.x ROOT.tcntl\n"
+USAGE="$USAGE \t -w: paw_wave.x ROOT.wcntl\n"
+USAGE="$USAGE \t -z: tail -f ROOT.prot\n"
 USAGE="$USAGE \t -0: dry-run (creates files but does not run jobs)\n"
 USAGE="$USAGE \t -v: verbose\n"
 USAGE="$USAGE \n"
@@ -81,8 +91,7 @@ function execute(){
 # string. 
 # use as FILE=$(findroot cntl)
 function findroot(){
-    local EXT=$1
-    local LIST=$(find . -iname "*.$EXT")
+    local LIST=$(echo *.$1)
     local RESULT=
     local X
     for X in $LIST; do
@@ -99,7 +108,7 @@ function findroot(){
 #-------------------------------------------------------------------------------
 #  resolve argument list
 #-------------------------------------------------------------------------------
-OPTSTRING=":hv0sdfw"
+OPTSTRING=":hv0afsdwtz"
 OPTIND=0
 while getopts "${OPTSTRING}" OPT  ; do
   case $OPT in
@@ -139,24 +148,14 @@ fi
 OPTIND=0  # reset argument position
 while getopts "${OPTSTRING}" OPT  ; do
  case $OPT in
-    f) # paw_fast.x $ROOT.cntl
-      Y=$(findroot cntl)
+    a) # paw_show -ce $ROOT
+      Y=$(findroot prot)
+      Y=${Y%.prot}
       if [[ -n $Y ]] ; then      
-        execute "paw_fast.x  $Y 1>out 2>&1 &"
+        execute "paw_show -ce $Y"
       else
         echo "error in $0 for option $OPT" >&2
-        echo "*.cntl file not unique or not present" >&2
-        exit 1
-      fi
-      ;;
-    s) # paw_strc.x -c 
-      Y=$(findroot strc_out)
-      Y=${Y%.strc_out}
-      if [[ -n $Y ]] ; then      
-        execute "paw_strc.x -c $Y"
-      else
-        echo "error in $0 for option $OPT" >&2
-        echo "ROOT not unique or no file *.strc_out present" >&2
+        echo "*.prot file not unique or not present" >&2
         exit 1
       fi
       ;;
@@ -173,14 +172,55 @@ while getopts "${OPTSTRING}" OPT  ; do
       if [[ -n $Y ]] ; then      
         execute "paw_dosplot.x $Y"
         Y=${Y%.dpcntl}
-        execute "xmgrace -batch $Y.bat"
+        execute "xmgrace -free -noask -batch $Y.bat"
       fi
       ;;
-    w) # paw_show -ce $ROOT
-      Y=$(findroot prot)
-      Y=${Y%.prot}
+    f) # paw_fast.x $ROOT.cntl
+      Y=$(findroot cntl)
       if [[ -n $Y ]] ; then      
-        execute "paw_show -ce $Y"
+        execute "paw_fast.x  $Y 1>out 2>&1 &"
+        execute "tail -f ${Y%.cntl}.prot"
+       else
+        echo "error in $0 for option $OPT" >&2
+        echo "*.cntl file not unique or not present" >&2
+        exit 1
+      fi
+      ;;
+    s) # paw_strc.x -c 
+      Y=$(findroot strc_out)
+      Y=${Y%.strc_out}
+      if [[ -n $Y ]] ; then      
+        execute "paw_strc.x -c $Y"
+      else
+        echo "error in $0 for option $OPT" >&2
+        echo "ROOT not unique or no file *.strc_out present" >&2
+        exit 1
+      fi
+      ;;
+    w) # paw_wave.x $ROOT.wcntl
+      Y=$(findroot wcntl)
+      if [[ -n $Y ]] ; then      
+        execute "paw_wave.x  $Y"
+      else
+        echo "error in $0 for option $OPT" >&2
+        echo "*.wcntl file not unique or not present" >&2
+        exit 1
+      fi
+      ;;
+    t) # paw_tra.x $ROOT.tcntl
+      Y=$(findroot tcntl)
+      if [[ -n $Y ]] ; then      
+        execute "paw_tra.x  $Y"
+      else
+        echo "error in $0 for option $OPT" >&2
+        echo "*.tcntl file not unique or not present" >&2
+        exit 1
+      fi
+      ;;
+    z) # tail -f $ROOT.prot
+      Y=$(findroot prot)
+      if [[ -n $Y ]] ; then      
+        execute "tail -f $Y"
       else
         echo "error in $0 for option $OPT" >&2
         echo "*.prot file not unique or not present" >&2
