bugfix in the scripts

diff --git a/src/Tools/Scripts/paw_collect b/src/Tools/Scripts/paw_collect
--- a/src/Tools/Scripts/paw_collect
+++ b/src/Tools/Scripts/paw_collect
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #################################################################
 #
 #  name: paw_collect: 
@@ -6,21 +6,47 @@
 #  purpose: collects total energies from CP-PAW projects
 #
 # searches through all *.prot files in the current directory, 
-# as well as one and two subdirectories down
+# as well as up to four subdirectories down
 # and lists the name of the project and the last total energy
-# written in the extended printout. The resulting list appears 
-# in the file pawcollect.out
-#
+# written in the extended printout. 
 #################################################################
-for DIR in . * */* */*/* */*/*/* */*/*/*/* ; do
-   if test -d $DIR ; then
-     for FILE in $DIR/*.prot; do
-       if test -e $FILE ; then
-         ENERGY=$(grep -i 'Total energy' $FILE \
-                 | tail -1 |sed s/H//g |sed s/TOTAL//g \
-                 |sed s/ENERGY//g |sed s/://g)
-         echo $FILE: $ENERGY
-       fi
-     done
-   fi
+export USAGE="Usage:
+\t     paw_collect options 
+Options:
+\t  -h: print this help message and exit
+Prints the total energies of all paw_projects in the current directory 
+and five directories down. The unit is Hartree.
+\n"
+
+while getopts :h OPT ; do
+  case $OPT in
+    h)
+      echo -e "$USAGE"
+      exit 0
+      ;;
+    \?)   # unknown option (placed into OPTARG, if OPTSTRING starts with :)
+      echo "error in $0" >&2
+      echo "invalid option -$OPTARG" >&2
+      echo "retrieve argument list with:" >&2
+      echo "$0 -h" >&2
+      exit 1
+      ;;
+    :)    # no argument passed to option requiring one
+      echo "error in $0" >&2
+      echo "option -$OPTARG requires an additional argument" >&2
+      exit 1
+      ;;  
+  esac
+done
+
+for FILE in         *.prot \
+                  */*.prot \
+                */*/*.prot \
+              */*/*/*.prot \
+            */*/*/*/*.prot ; do
+  if [[ -f $FILE ]] ; then
+    ROOT=${FILE%.prot}
+    ENERGY=$(paw_get -nw etot -- $ROOT)
+    echo -e "$ROOT $ENERGY"
+  fi
 done
