rebuid the entire testsuite

diff --git a/src/Tools/Scripts/paw_get b/src/Tools/Scripts/paw_get
--- a/src/Tools/Scripts/paw_get
+++ b/src/Tools/Scripts/paw_get
@@ -23,28 +23,131 @@ USAGE="$USAGE \t\t whatid=homo  \t prints energy of the highest occupied \
                                           state in eV\n"
 USAGE="$USAGE \t\t whatid=lumo  \t prints energy of the lowest unoccupied \
                                           state in eV\n"
-USAGE="$USAGE \t -n prints the result as number (levels in eV, total \
-                            energies in Hartree) or accordung to -u\n"
+USAGE="$USAGE \t\t whatid=volume   \t prints volume of the unit cell \n"
+USAGE="$USAGE \t -n prints the result as number or according to -u\n"
 USAGE="$USAGE \t -t prints the result as text (default)\n"
-USAGE="$USAGE \t -u unit: ev|kj/mol|kcal/mol|h (only for -n) \n"
+USAGE="$USAGE \t -u unit: ev|kj/mol|kcal/mol|h|angstrom^3|aa^3|cubangstrom|a0^3|abohr^3|cubabohr \n"
 USAGE="$USAGE \t -v verbose\n"
 USAGE="$USAGE \t -h prints this help message\n"
-#
+#-------------------------------------------------------------------------------
+#  implement dry-run
+#-------------------------------------------------------------------------------
+function execute(){
+    # || is "or" in [[...]], && is "and" in [[..]]
+    if [[ "${DRYRUN}" = "yes" || "${VERBOSE}" = "yes" ]] ; then
+      echo "${@}"
+    fi
+    if [[ "${DRYRUN}" = "no" ]] ; then
+      eval "$@"
+    fi
+}
+#-------------------------------------------------------------------------------
+#  implement unit conversion
+#-------------------------------------------------------------------------------
+function convertunit(){
+  # takes a string as argument containing a number and a unit string.
+  # returns a new variable "AUVALUE" in hartree atomic units
+  local NEWUNIT=$1
+  local ARGSTRING=$2
+  local ARGVALUE=$(echo "$ARGSTRING" | awk '{print $1}')
+  local ARGUNIT=$(echo "$ARGSTRING" | awk '{print $2}')
+  #
+  local HARTREE=1.
+  local EV=$(echo "scale=8; 1. / 27.211 " | bc -l)
+  local KJBYMOL=$(echo "scale=8; 1. / 2625.500223430069 " | bc -l)
+  local KCALBYMOL=$(echo "scale=8; 1. / 627.5096463920391 " | bc -l)
+  local ANGSTROM=$(echo "scale=8; 1. / 0.529177 " | bc -l)
+  local CUBANGSTROM=$(echo "scale=8; $ANGSTROM ^ 3 " | bc -l)
+  local ABOHR=1.
+  local CUBABOHR=1.
+  #
+  local NEWVALUE
+  case "$ARGUNIT" in
+    H) NEWVALUE=$(echo "scale=8; $ARGVALUE * $HARTREE " | bc -l) 
+       ;;
+    EV) NEWVALUE=$(echo "scale=8; $ARGVALUE * $EV " | bc -l) 
+       ;;
+    KJ/MOL) NEWVALUE=$(echo "scale=8; $ARGVALUE * $KJBYMOL " | bc -l) 
+       ;;
+    KCAL/MOL) NEWVALUE=$(echo "scale=8; $ARGVALUE * $KCALBYMOL " | bc -l) 
+       ;;
+    ANGSTROM) NEWVALUE=$(echo "scale=8; $ARGVALUE * $ANGSTROM " | bc -l) 
+       ;;
+    CUBANGSTROM) NEWVALUE=$(echo "scale=8; $ARGVALUE * $CUBANGSTROM " | bc -l) 
+       ;;
+    ABOHR) NEWVALUE=$(echo "scale=8; $ARGVALUE * $ABOHR " | bc -l) 
+       ;;
+    CUBABOHR) NEWVALUE=$(echo "scale=8; $ARGVALUE * $CUBABOHR " | bc -l) 
+       ;;
+    *)
+      echo "error in $0; (in function toatomicunits)" >&2
+      echo "ARGUNIT=$ARGUNIT not recognized" >&2
+      exit 1  
+      ;;
+  esac
+  case "$NEWUNIT" in
+    H) NEWVALUE=$(echo "scale=8; $NEWVALUE / $HARTREE " | bc -l) 
+       ;;
+    EV) NEWVALUE=$(echo "scale=8; $NEWVALUE / $EV " | bc -l) 
+       ;;
+    KJ/MOL) NEWVALUE=$(echo "scale=8; $NEWVALUE / $KJBYMOL " | bc -l) 
+       ;;
+    KCAL/MOL) NEWVALUE=$(echo "scale=8; $NEWVALUE / $KCALBYMOL " | bc -l) 
+       ;;
+    ANGSTROM) NEWVALUE=$(echo "scale=8; $NEWVALUE / $ANGSTROM " | bc -l) 
+       ;;
+    CUBANGSTROM) NEWVALUE=$(echo "scale=8; $NEWVALUE / $CUBANGSTROM " | bc -l) 
+       ;;
+    ABOHR) NEWVALUE=$(echo "scale=8; $NEWVALUE / $ABOHR " | bc -l) 
+       ;;
+    CUBABOHR) NEWVALUE=$(echo "scale=8; $NEWVALUE / $CUBABOHR " | bc -l) 
+       ;;
+    *)
+      echo "error in $0; (in function toatomicunits)" >&2
+      echo "NEWUNIT=$NEWUNIT not recognized" >&2
+      exit 1  
+      ;;
+  esac
+  #
+  echo "$NEWVALUE $NEWUNIT"
+}
+################################################################################
 #  resolve input arguments
 #  $TN is "T" fort text output and "N" for number output
-#
+################################################################################
 export TN=T
 export WHATID="etot"
 export VERBOSE=no
 export UNIT=""
 while getopts :hw:tnp:vu: OPT ; do
   case $OPT in 
-    w) WHATID="$OPTARG" ;;
+    w) WHATID="$OPTARG" 
+       case $WHATID in
+         etot|gap|homo|lumo|efermi|volume) 
+         ;; 
+         *)
+           echo "error in $0: illegal argument $WHATID of option -w" >&2
+           exit 1
+         ;;
+       esac
+       ;;
     n) TN=N             ;;
     t) TN=T             ;;
-    u) UNIT=$OPTARG     ;;
+    u) UNIT=$OPTARG     
+       UNIT=$(echo $UNIT | tr '[:upper:]' '[:lower:]') #convert to lower case
+       case $UNIT in 
+         h)        UNIT="H" ;;
+         ev)       UNIT="EV" ;;
+         kj/mol)   UNIT="KJ/MOL" ;;
+         kcal/mol) UNIT="KCAL/MOL" ;;
+         angstrom^3|cubangstrom|aa^3) UNIT="CUBANGSTROM" ;;
+         abohr^3|cubabohr|a0^3) UNIT="CUBABOHR" ;;
+         *) echo "error in $0: argument $OPTARG for -u not recognized" >&2
+             exit 1 ;;
+       esac
+       ;;
     v) VERBOSE=yes      ;;
-    h) echo -e $USAGE   ;;
+    h) echo -e $USAGE ; exit 0  ;;
     \?)   # unknown option (placed into OPTARG, if OPTSTRING starts with :)
       echo "error in $0" >&2
       echo "invalid option -$OPTARG" >&2
@@ -62,60 +165,32 @@ done
 shift $(($OPTIND - 1))
 ROOT=$1
 #
-#   scan for allowed values of WHATID
+# report input variables -------------------------------------------------------
 #
-case $WHATID in
-  etot)   WHAT="TOTAL ENERGY" ;;
-  gap)    WHAT="ABSOLUTE GAP" ;;
-  homo)   WHAT="HOMO-ENERGY"  ;;
-  lumo)   WHAT="LUMO-ENERGY"  ;;
-  efermi) WHAT="CHEMICAL POTENTIAL"  ;;
-  *)
-    echo "error in $0: illegal argument $WHATID of option -w" >&2
-    exit 1
-    ;;
-esac
-#
-if [[ -n $UNIT ]] ; then
-  case $WHATID in
-    etot)   EUNIT=1. ;;
-    gap)    EUNIT=0.0367498438 ;;
-    homo)   EUNIT=0.0367498438 ;;
-    lumo)   EUNIT=0.0367498438 ;;
-    efermi) EUNIT=0.0367498438 ;;
-    *)
-      echo "error in $0: illegal argument $WHATID of option -w" >&2
-      exit 1
-      ;;
-  esac
-  #
-  case $UNIT in 
-     ev)       EUNIT=$(echo "$EUNIT * 27.211" | bc -l)   ;;
-     kj/mol)   EUNIT=$(echo "$EUNIT * 2625.500223430069" | bc -l) ;;
-     kcal/mol) EUNIT=$(echo "$EUNIT * 627.5096463920391" | bc -l) ;;
-     h)   ;;
-     *) echo "error in $0: argument $OPTARG for -u not recognized" >&2
-        exit 1
-        ;;
-  esac
+if [[ $VERBOSE = yes ]] ; then
+  echo WHATID..................: $WHATID
+  echo PROJECT NAME............: $ROOT
+  echo UNIT....................: $UNIT
+  echo VERBOSE.................: $VERBOSE
+  echo text or numerical output: $TN
 fi
 #
-# is rootname defined
+################################################################################
+#  check input
+################################################################################
+#
+# is rootname defined ? --------------------------------------------------------
 #
 if [[ -z $ROOT ]] ; then
   echo error: missing argument. specify root name of the paw_project
   exit 1
 fi
 #
-# report input variables
+#  is the output unit been specified? ------------------------------------------
 #
-if [[ $VERBOSE = yes ]] ; then
-  echo WHATID..................: $WHATID
-  echo WHAT....................: $WHAT
-  echo PROJECT NAME............: $ROOT
-  echo UNIT....................: $UNIT
-  echo VERBOSE.................: $VERBOSE
-  echo text or numerical output: $TN
+if [[ -z $UNIT ]] ; then
+  echo error: missing argument -u. specify UNIT
+  exit 1
 fi
 #
 # Does protocoll file exist?
@@ -125,12 +200,48 @@ if [[ ! -e $ROOT.prot ]] ; then
   echo "specified protocoll file: $ROOT.prot" >&2
   exit 1
 fi
-export RESULT=$(grep "$WHAT" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
 #
-#  correction for mermin vs. non-mermin output
+# Is the unit consistent with quantity?
 #
-if [[ -z  "$RESULT" ]] ; then
-  if [[ "$WHAT" = "CHEMICAL POTENTIAL" ]]  ; then 
+case $WHATID in
+  etot|gap|homo|lumo|efermi)
+    case $UNIT in
+      H|EV|KJ/MOL|KCAL/MOL) ;;
+      *)
+        echo "error in $0: unit inconsistency" >&2
+        echo "energy variable $WHATID inconsistent with unit $UNIT" >&2
+        exit 1
+        ;;
+    esac
+    ;;
+  volume) 
+    case $UNIT in
+      ABOHR^3|CUBABOHR|ANGSTROM^3|CUBANGSTROM) ;;
+      *)
+        echo "error in $0: unit inconsistency" >&2
+        echo "volume variable $WHATID inconsistent with unit $UNIT" >&2
+        exit 1
+        ;;
+    esac
+    ;;
+esac
+#
+################################################################################
+#  collect data in a.u.
+################################################################################
+#
+#--------------  total energy --------------------------------------------------
+#
+if [[ "$WHATID" = "etot" ]]  ; then 
+  WHAT="TOTAL ENERGY"
+  export RESULT=$(grep "$WHAT" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+#
+#--------------  fermi level ---------------------------------------------------
+#
+elif [[ "$WHATID" = "efermi" ]]  ; then 
+  WHAT="CHEMICAL POTENTIAL" 
+  export RESULT=$(grep "$WHAT" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+  if [[ -z  "$RESULT" ]] ; then # fall-back for insulators
     export WHAT1="HOMO-ENERGY" 
     export RESULT1=$(grep "$WHAT1" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
     RESULT1=${RESULT1%EV*}
@@ -141,41 +252,83 @@ if [[ -z  "$RESULT" ]] ; then
     RESULT="$RESULT EV"  
     if [[ -z $RESULT1 ]] ; then RESULT='';  fi
     if [[ -z $RESULT2 ]] ; then RESULT='';  fi
-  #
-  elif [[ "$WHAT" = "HOMO-ENERGY" ]] ; then
-    export WHAT1="CHEMICAL POTENTIAL" 
-    export RESULT=$(grep "$WHAT1" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
-  #
-  elif [[ "$WHAT" = "LUMO-ENERGY" ]] ; then
-    export WHAT1="CHEMICAL POTENTIAL" 
-    export RESULT=$(grep "$WHAT1" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
   fi
+#
+#--------------  band gap ------------------------------------------------------
+#
+elif [[ "$WHATID" = "gap" ]] ; then
+  WHAT="ABSOLUTE GAP"
+  export RESULT=$(grep "$WHAT" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+  if [[ -z $RESULT ]] ; then  
+    echo "error in $0: calculation with variable occupations: gap is unknown."
+    exit 1
+  fi
+#
+#--------------  homo  ---------------------------------------------------------
+#
+elif [[ "$WHATID" = "homo" ]] ; then
+  export WHAT="HOMO-ENERGY"  
+  export RESULT=$(grep "$WHAT" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+  if [[ -z $RESULT ]] ; then  # fall back for metals
+    export WHAT="CHEMICAL POTENTIAL"  
+    export RESULT=$(grep "$WHAT" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+  fi
+#
+#--------------  lumo  ---------------------------------------------------------
+#
+elif [[ "$WHATID" = "lumo" ]] ; then
+  export WHAT="LUMO-ENERGY" 
+  export RESULT=$(grep "$WHAT" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+  if [[ -z $RESULT ]] ; then  # fall back for metals
+    export WHAT="CHEMICAL POTENTIAL"  
+    export RESULT=$(grep "$WHAT" $ROOT.prot | tail -n1 | awk -F: '{print $2}')
+  fi
+#
+#--------------  volume  -------------------------------------------------------
+#
+elif [[ "$WHATID" = "volume" ]] ; then
+  ##  cannot grep for "[". therefore enclose in "[ ]", i.e. [[]
+  WHAT='[[]ANGSTROM[]]'
+  export T11=$(grep "T1$WHAT" $ROOT.prot | tail -n1 | awk '{print $2}')
+  export T12=$(grep "T1$WHAT" $ROOT.prot | tail -n1 | awk '{print $3}')
+  export T13=$(grep "T1$WHAT" $ROOT.prot | tail -n1 | awk '{print $4}')
+  export T21=$(grep "T2$WHAT" $ROOT.prot | tail -n1 | awk '{print $2}')
+  export T22=$(grep "T2$WHAT" $ROOT.prot | tail -n1 | awk '{print $3}')
+  export T23=$(grep "T2$WHAT" $ROOT.prot | tail -n1 | awk '{print $4}')
+  export T31=$(grep "T3$WHAT" $ROOT.prot | tail -n1 | awk '{print $2}')
+  export T32=$(grep "T3$WHAT" $ROOT.prot | tail -n1 | awk '{print $3}')
+  export T33=$(grep "T3$WHAT" $ROOT.prot | tail -n1 | awk '{print $4}')
+  DETSTRING=" $T11 * ( $T22 * $T33 - $T23 * $T32 ) \
+            + $T12 * ( $T23 * $T31 - $T21 * $T33 ) \
+            + $T13 * ( $T21 * $T32 - $T22 * $T31 ) "
+  export RESULT=$(echo " scale=5;  ${DETSTRING} " | bc -l )
+  RESULT="$RESULT CUBANGSTROM"
+else
+  echo "error in $0: $WHAT is not a permitted value for WHAT"
+  exit 1
 fi
-
-#
-#  test if result is non-empty
-#
+#  test if result is empty
 if [[ -z  "$RESULT" ]] ; then
-  echo error in $0: no result found in $ROOT.prot
+  echo "error in $0: no result found in $ROOT.prot"
   exit 1
 fi
 #
+################################################################################
+#  convert units
+################################################################################
+RESULT=$(convertunit $UNIT "$RESULT") #internal function convertunit
+#
+################################################################################
 #  switch between number and text output and edit result
+################################################################################
+if [[ $TN = N ]] ; then 
+  RESULT=$(echo "$RESULT" | awk '{print $1}')
+else
+  RESULT=$(echo "$WHATID = $RESULT for $ROOT")
+fi
 #
-case $TN in
-  N) 
-    RESULT=${RESULT%H*}
-    RESULT=${RESULT%EV*}
-    if [[ -n $UNIT ]] ; then 
-      RESULT=$(echo "$RESULT * $EUNIT" | bc -l)
-    fi
-    ;;
-  *) 
-    RESULT=$(echo "$WHAT = $RESULT for $ROOT")
-    ;;
-esac
-#
+################################################################################
 #  report result
-#
-echo $RESULT
+################################################################################
+echo "$RESULT"
 exit 0
