modified paw_scanlat and paw_waittillempty

diff --git a/src/Tools/Scripts/paw_scanlat b/src/Tools/Scripts/paw_scanlat
--- a/src/Tools/Scripts/paw_scanlat
+++ b/src/Tools/Scripts/paw_scanlat
@@ -8,7 +8,9 @@
 #       OPTIONS: mandatory: p optional: hlubej0v 
 #
 #   DESCRIPTION: perform a sequence of paw calculations with different
-#                lattice constants or updates data files with its results
+#                lattice constants or updates data files with its results.
+#                produces the file murn.dat, which specifies the total energy
+#                vs. LUNIT^3. 
 #
 #       OPTIONS:
 #          -h    print this help message
@@ -16,11 +18,12 @@
 #          -l    list of percent changes of the lattice constant
 #                 (enter in apostrophes such as "98 100 102")
 #                default: "96 97 98 99 100 101 102 103 104"
-#          -u    updates result data files (no paw simulations)
-#          -e    paw_command
-#          -j nr. of paw_jobs allowed to run simultaneously
-#          -0 dry-run (reconstruct *.dat files only)
-#          -v verbose
+#          -u    only update of data files. No paw simulations
+#                if -u is absent the calculations are performed, but not updated
+#          -e    paw_command (default paw_fast.x)
+#          -j    nr. of paw_jobs allowed to run simultaneously (default 8)
+#          -0    dry-run (reconstruct *.dat files only)
+#          -v    verbose
 #
 #  prerequisites: nio.cntl 
 #                 nio.strc 
@@ -28,10 +31,23 @@
 #
 #  performs set of calculations for different lattice constants.
 #
+#  1) starts from a rootname ROOT specified as project by the option
+#     -p.  ROOT may contain the full path or the relative path with
+#     respect to the current directory of the parent process. As
+#     precondition there is a file $ROOT.cntl and a file $ROOT.strc
+#
+#  2) with the option -l a list of percentage changes of the lattice
+#     constant is provided
+#
+#  3) For each percentage change $X of the lattice constant in the
+#     list, a calculation is performed in its own directory
+#     ${DIROFX}=${ROOT}_$X. The rootname of this project is
+#     ${ROOTOFX}=${DIROFX}/${DIROFX##*/}.
+#
 #  nio.strc must contain exactly one line containing "LUNIT=" 
 #  followed by the lattice constant in atomic units, or "LUNIT[AA]="
 #  followed by the lattice constant in angstrom, followed by "!END".
-#  this occurrance will be replaced by the varied values for the 
+#  this occurrence will be replaced by the modified values for the 
 #  individual runs.
 #
 #  specify k-points in the structure file with !STRUCTURE!KPOINTS:DIV=
@@ -61,7 +77,8 @@ USAGE="$USAGE \n"
 USAGE="$USAGE \t paw_scanlat options\n"
 USAGE="$USAGE \n"
 USAGE="$USAGE Options:\n"
-USAGE="$USAGE \t -p rootname of the project to be considered (mandatory)\n"
+USAGE="$USAGE \t -p projectname of the project to be considered (mandatory)\n"
+# assumption: project name does not contain the directory
 USAGE="$USAGE \t -l list of percent changes of the lattice constant\n"
 USAGE="$USAGE \t    (enter in apostrophes \"...\")\n"
 USAGE="$USAGE \t     \"96 97 98 99 100 101 102 103 104\"\n"
@@ -105,19 +122,55 @@ function execute(){
       export PID=$!
     fi
 }
-   #
+#-------------------------------------------------------------------------------
+#  strip leading and trailing whitespace from a bash variable
+#-------------------------------------------------------------------------------
+function stripwhitespace {
+##########################################################################
+# strips leading and trailing space characters from the variable
+# passed as argument. 
+#
+# -- [:space:] is a posix character class which includes tab, newline,
+#  vertical tab, form feed, carriage return, and space.
+# -- *([:space:]) is a regular expression for zero or more spaces.
+# -- ${X#RegEx} removes the shortest leading match of the regular
+#  expression RegEx in the variable X
+# -- ${X%RegEx} removes the shortest trailing match of the regular
+#  expression RegEx in the variable X
+##########################################################################
+local X=$1    # use all arguments as one string. 
+X=${X##*([:space:])} # remove leading whitespace characters
+X=${X%%*([:space:])} # remove trailing whitespace characters
+echo "$X"
+}
+#-------------------------------------------------------------------------------
+#  count the number of running jobs with PID in PIDS
+#-------------------------------------------------------------------------------
+function countjobs {
+################################################################################
+## returns the number of active jobs on a list PIDS on project id-s           ##
+###############################################################################
+  local NACTIVE=0
+  local X
+  for X in ${PIDS} ; do
+    if [[ -n  $(ps -p $X -o pid= ) ]] ; then  NACTIVE=$(( $NACTIVE + 1 )); fi
+  done
+echo $NACTIVE
+}
+#
 #-------------------------------------------------------------------------------
 #  resolve argument list
 #-------------------------------------------------------------------------------
+export NAME # root name of the project including relative of absolute path
 ALATLIST="96 97 98 99 100 101 102 103 104"
 DRYRUN=no
 VERBOSE=no
 UPDATE=no
-NJOBS=3
+NJOBS=8
 while getopts :h0e:p:l:j:uv OPT ; do
   case $OPT in
     p)
-      NAME=$OPTARG
+      ROOT=$OPTARG
       ;;
     l)
       ALATLIST=$OPTARG
@@ -156,79 +209,118 @@ while getopts :h0e:p:l:j:uv OPT ; do
 done
 shift $(($OPTIND - 1))
 if [[ -e $1 ]] ; then echo "error in $0: argument present. none expected" >&2; fi
-if [[ -z $NAME ]] ; then
+if [[ -z $ROOT ]] ; then
   echo "error in $0: mandatory option -p missing" >&2
+  exit 1
+fi
+if [[ ! -f $ROOT.strc ]] ; then
+  echo "error in $0: file $ROOT.strc is missing" >&2
+  exit 1
+fi
+if [[ ! -f $ROOT.cntl ]] ; then
+  echo "error in $0: file $ROOT.strc is missing" >&2
   exit 1
 fi
 #
 # when PAWCMD has not been defined via arguments, set default
 if [[ -z $PAWCMD ]] ; then
-  PAWCMD="paw_waittillempty -n $NJOBS ; paw_fast.x"
+  PAWCMD="paw_fast.x"
 fi
 #
 #   report setting of variables
 #   
 if [ $VERBOSE = yes ] ; then
-  echo "root name of the project...................: ${NAME}"
+  echo "root name of the project...................: ${ROOT}"
   echo "list of percent changes of lattice constant: ${ALATLIST}"
   echo "paw_command................................: ${PAWCMD}"
   echo "dry-run....................................: ${DRYRUN}"
   echo "update.....................................: ${UPDATE}"
-  echo "max. nr. of paw jobs running simultaneously: ${NJOBS}"
+  echo "max. nr. of jobs running simultaneously....: ${NJOBS}"
 fi
 #
 #==============================================================================
-# pick out the equilibrium lattice constant from the structure file
+# Divide root into a directory opart and a non-directory part
 #==============================================================================
-if [[ -n $(grep 'LUNIT\[AA\]=' $NAME.strc) ]]; then
-  X=$(grep -i 'LUNIT\[AA\]=' $NAME.strc)  #pick the line containing LUNIT
-  X=${X#*[Ll][Uu][Nn][Ii][Tt]\[[Aa][Aa]\]=}
+export NAME=${ROOT##*/}     # non-directort  part of $ROOT
+export DIR=${ROOT%${NAME}}  # directory part of $ROOT
+if [[ -z ${DIR} ]] ; then 
+  DIR=${THISDIR} 
+else
+  DIR=${THISDIR}/${DIR##${THISDIR}}
+fi
+ROOT=${DIR}/${NAME}
+if [ $VERBOSE = yes ] ; then echo DIR =\"${DIR}\" ; fi
+if [ $VERBOSE = yes ] ; then echo NAME=\"${NAME}\" ; fi
+if [ $VERBOSE = yes ] ; then echo ROOT=\"${ROOT}\" ; fi
+#
+#==============================================================================
+# pick out the reference lattice constant from the structure file
+#==============================================================================
+LINE=$(grep 'LUNIT' $ROOT.strc)
+echo "LINE(1) ${LINE}"
+LINE=${LINE#*[Ll][Uu][Nn][Ii][Tt]} #strip everything up to LUNIT
+echo "LINE(2) $LINE"
+if [[ -n ${LINE%%\[AA\]=*} ]] ; then
+  echo unit is bohr
   AA=$(echo "1. / 0.529177" | bc -l )   # conversion factor into atomic units
 else
-  X=$(grep 'LUNIT=' $NAME.strc)  #pick the line containing LUNIT
-  X=${X#*[Ll][Uu][Nn][Ii][Tt]=}
+  echo unit is angstrom
   AA=$(echo "1." | bc -l )
 fi
-X=${X%%!END*}
-ALAT0=$X
+#echo "LINE(3) $LINE"
+LUNIT=${LINE#*=} # remove all till next preceeding equal sign (such as [AA])
+#echo "LUNIT(1) --$LUNIT--"
+LUNIT=$(stripwhitespace "$LUNIT") # stripwhitespace is a function
+                                  # defined above. Keep the
+                                  # apostrophes around $LUNIT, so that
+                                  # it is interpreted as one string
+                                  # with spaces rather than an array
+                                  # of strings separated by spaces
+LUNIT=${LUNIT%%[[:space:]]*} # remove trailing text
+ALAT0=$LUNIT
+if [ $VERBOSE = yes ] ; then echo ALAT0=\"${ALAT0}\"; fi
 #
 #==============================================================================
 # loop crystal calculation through different lattic constants                ==
 #==============================================================================
 if [[ $UPDATE = no ]] ; then
-  export PIDS=
+  export PIDS="" # list of project id's
   for X in $ALATLIST; do
     if [[ $VERBOSE = yes ]] ; then echo doing $X ; fi 
-
-    export ROOT=${NAME}_${X}
-    export PDIR=${ROOT%/*}   # project directory
-    export PNAME=${ROOT##*/} # project name w/o Dir.
-    if [[ ! -d $ROOT ]] ; then mkdir $ROOT ; fi
+    export DIROFX=${DIR}/${NAME}_$X
+    export ROOTOFX=${DIROFX}/${NAME}_$X
+    export ALATX=$(echo "$X /100 * $ALAT0 " | bc -l)
+    if [[ $VERBOSE = yes ]] ; then echo DIROFX=${DIROFX} ; fi 
+    if [[ $VERBOSE = yes ]] ; then echo ROOTOFX=${ROOTOFX} ; fi 
+    if [[ $VERBOSE = yes ]] ; then echo ALATOFX=${ALATX} ; fi 
+    if [[ ! -d $DIROFX ]] ; then mkdir ${DIROFX} ; fi
 
     #===========================================================================
     # construct structure control file from template by replacing alat
     #===========================================================================
-    ALAT=$(echo "$X /100 * $ALAT0 " | bc -l)
-    execute "sed \"/[Ll][Uu][Nn][Ii][Tt]/s/${ALAT0}/${ALAT} /g\" \
-                                         ${NAME}.strc >$ROOT/${NAME}_${X}.strc"
+    execute "sed \"/[Ll][Uu][Nn][Ii][Tt]/s/${ALAT0}/${ALATX} /g\" \
+                                         ${ROOT}.strc >${ROOTOFX}.strc"
     #==========================================================================
     # run paw_fast.x and place data "gap.dat" and "etot.dat"
     #==========================================================================
-    execute "cp ${NAME}.cntl $ROOT/${NAME}_${X}.cntl"
-    if [[ ! -e $ROOT/${NAME}_${X}.rstrt ]] ; then
-      if [[ -e ${NAME}.rstrt ]] ; then
-        execute "cp ${NAME}.rstrt $ROOT/${NAME}_${X}.rstrt"
+    execute "cp ${ROOT}.cntl ${ROOTOFX}.cntl"
+    if [[ ! -e ${ROOTOFX}.rstrt ]] ; then
+      if [[ -e ${ROOT}.rstrt ]] ; then
+        execute "cp ${ROOT}.rstrt ${ROOTOFX}.rstrt"
       else
         # test, whether restart file is required
-        if [[ -z $(grep START=*T  ${PDIR}/${NAME}_${X}.cntl) ]]; then 
-          echo "source restart file ${NAME}.rstrt does not exist"
+        if [[ -z $(grep START=*T  ${ROOTOFX}.cntl) ]]; then 
+          echo "source restart file ${ROOTOFX}.rstrt does not exist"
           exit 1
         fi
       fi
     fi
-    
-    execute "cd ${PDIR}"
-    execute "${PAWCMD} ${NAME}_${X}.cntl 1>${NAME}_${X}.out 2>&1 &" 
+    #
+    # pause if the number of active jobs exceeds maximum
+    while [[ $(countjobs) -ge ${NJOBS} ]] ; do sleep 2; done
+    #
+    execute "cd ${DIROFX}"
+    execute "${PAWCMD} ${ROOTOFX}.cntl 1>${ROOTOFX}.out 2>&1 &" 
     PIDS="$PIDS $PID"   # store the project id returned by 'execute'
     execute "cd ${THISDIR}"
   done
@@ -237,15 +329,17 @@ fi
 #============================================================================
 #==  wait until all submitted jobs ($PIDS) are finished
 #============================================================================
-export NACTIVE=1
-while [ ${NACTIVE} -gt 0 ] ; do
-  echo No.Jobs=$NACTIVE Date=`date` waiting....
-  sleep  1s
-  NACTIVE=0
-  for X in ${PIDS} ; do
-    if [[ -n  $(ps -p $X -o pid= ) ]] ; then  NACTIVE=$(( $NACTIVE + 1 )); fi
-  done
-done
+while [[ $(countjobs) -gt 0 ]] ; do sleep 2; done
+
+# export NACTIVE=1
+# while [ ${NACTIVE} -gt 0 ] ; do
+#   NACTIVE=0
+#   for X in ${PIDS} ; do
+#     if [[ -n  $(ps -p $X -o pid= ) ]] ; then  NACTIVE=$(( $NACTIVE + 1 )); fi
+#   done
+#   echo "No.Jobs=$NACTIVE; time=$(date "+ %H:%M:%S"); waiting...."
+#   sleep 2
+# done
 #
 #==============================================================================
 # update data files
@@ -255,31 +349,39 @@ if [[ $UPDATE = yes ]] ; then
   if [[ -e gap.dat ]]  ; then rm gap.dat; fi
   if [[ -e murn.in ]]  ; then rm murn.in; fi
   for X in $ALATLIST; do
-    if [[ $VERBOSE = yes ]] ; then echo "collecting ${NAME}_$X" ; fi
-    export ROOT=${NAME}_${X}
-    execute "cd ${ROOT}"
-    # paw_get does not work for metals.
-#    echo ${X} $(paw_get -w gap -u ev -n ${NAME}_${X}) >>${THISDIR}/gap.dat
-    echo ${X} $(paw_get -w etot -u H -n ${NAME}_${X}) >>${THISDIR}/etot.dat
-    ALAT=$(echo "$X /100 * $ALAT0 " | bc -l)
-    Y=$(echo "$ALAT * $AA" | bc -l)
-    Y=$(echo "$Y * $Y * $Y " | bc -l)
-    echo ${Y} $(paw_get -w etot -u H -n ${NAME}_${X}) >>${THISDIR}/murn.in
+    if [[ $VERBOSE = yes ]] ; then echo collecting $X ; fi 
+    export DIROFX=${DIR}/${NAME}_$X
+    export ROOTOFX=${DIROFX}/${NAME}_$X
+    export ALATX=$(echo "$X /100 * $ALAT0 " | bc -l)
+    if [[ $VERBOSE = yes ]] ; then echo DIROFX=${DIROFX} ; fi 
+    if [[ $VERBOSE = yes ]] ; then echo ROOTOFX=${ROOTOFX} ; fi 
+    if [[ $VERBOSE = yes ]] ; then echo ALATOFX=${ALATX} ; fi 
+
+    # paw_get -w gap does not work for metals.
+    # echo ${X} $(paw_get -w gap -u ev -n ${ROOTOFX}) >>${DIR}/gap.dat
+    echo ${X} $(paw_get -w etot -u H -n ${ROOTOFX})   >>${DIR}/etot.dat
+    Y=$(echo "$ALATX * $AA" | bc -l)
+    Y=$(echo "$Y * $Y * $Y " | bc -l) 
+    # write (LUNIT-in-abohr^3) (energy per unit cell in hartree)
+    echo ${Y} $(paw_get -w etot -u H -n ${ROOTOFX}) >>${DIR}/murn.in
+    if [[ $VERBOSE = yes ]] ; then 
+      echo Y=${Y} ETOT=$(paw_get -w etot -u H -n ${ROOTOFX}) 
+    fi
     #
     #  clean up
     # 
     if [[ "$DRYRUN" = "no" ]] ; then
-      LIST="${NAME}_${X}_constr.report ${NAME}_${X}_r.tra ${NAME}_${X}.pdos \
-            ${NAME}_${X}.strc_out "
+      LIST="${ROOTOFX}_constr.report ${ROOTOFX}_r.tra ${ROOTOFX}.pdos \
+            ${ROOTOFX}.strc_out "
       for Y in $LIST ; do
         if [[ $VERBOSE = yes ]] ; then echo cleaning $Y ; fi
         if [[ -e $Y ]] ; then rm $Y ; fi
       done
-      for Y in ${NAME}_${X}_stpfor*.myxml; do
+      for Y in ${ROOTOFX}_stpfor*.myxml; do
         if [[ -e $Y ]] ; then rm $Y ; fi
       done
     fi
-    execute "cd ${THISDIR}"
   done
 fi
+execute "cd ${THISDIR}"
 exit 0
