changed tool paw_do. Added function in paw_scanlat: scanlat can be started from a common restart file.

diff --git a/src/Tools/Scripts/paw_do b/src/Tools/Scripts/paw_do
--- a/src/Tools/Scripts/paw_do
+++ b/src/Tools/Scripts/paw_do
@@ -11,19 +11,21 @@
 #
 #       OPTIONS:
 #          -h    print this help message
-#          -f    execute paw_fast.x
-#          -d    execute paw_dos.x and paw_dosplot.x
-#          -s    execute paw_strc.x
-#          -w    execute paw_wave.x
-#          -t    execute paw_tra.x
-#          -a    execute paw_show -ce
-#          -z    execute tail -f ROOT.prot
 #          -0:   dry-run
-#          -b:   directory containing the paw executables
 #          -v:   verbose
+#          -F    execute paw_fast.x
+#          -P    execute doppaw (ppaw_fast.x)
+#          -D    execute paw_dos.x and paw_dosplot.x
+#          -S    execute paw_strc.x
+#          -W    execute paw_wave.x
+#          -T    execute paw_tra.x
+#          -A    execute paw_show -ce
+#          -Z    execute tail -f ROOT.prot
+#       uppercase options are chosen to select a particular tool. Lowercase
+#       options (except hv0) are treated as options for the preceeding tool 
 #
 #  Example:
-#       paw_do -f si2
+#       paw_do -F 
 #
 #   REQUIREMENTS: 
 #                  paw_dos.x,paw_dosplot.x,paw_show,paw_fast,paw_strc.x
@@ -48,19 +50,19 @@ USAGE="$USAGE \t frontend for paw code and tools"
 USAGE="$USAGE \n"
 USAGE="$USAGE Options:\n"
 USAGE="$USAGE \t -h \t print this help message \n"
-USAGE="$USAGE \t -a: paw_show -ce ROOT\n"
-USAGE="$USAGE \t -f: paw_fast.x ROOT.cntl 1>out 2>&1 & \n"
-USAGE="$USAGE \t -d: paw_dos.x ROOT.dcntl \n"
+USAGE="$USAGE \t -A: paw_show -ce ROOT\n"
+USAGE="$USAGE \t -F: paw_fast.x ROOT.cntl 1>out 2>&1 & \n"
+USAGE="$USAGE \t -D: paw_dos.x ROOT.dcntl \n"
 USAGE="$USAGE \t\t   paw_dosplot.x ROOT.dpcntl; xmgrace -batch ROOT.bat\n"
-USAGE="$USAGE \t -s: paw_strc.x -c ROOT\n"
-USAGE="$USAGE \t -t: paw_tra.x ROOT.tcntl\n"
-USAGE="$USAGE \t -w: paw_wave.x ROOT.wcntl\n"
-USAGE="$USAGE \t -z: tail -f ROOT.prot\n"
+USAGE="$USAGE \t -S: paw_strc.x -c ROOT\n"
+USAGE="$USAGE \t -T: paw_tra.x ROOT.tcntl\n"
+USAGE="$USAGE \t -W: paw_wave.x ROOT.wcntl\n"
+USAGE="$USAGE \t -Z: tail -f ROOT.prot\n"
 USAGE="$USAGE \t -0: dry-run (creates files but does not run jobs)\n"
 USAGE="$USAGE \t -v: verbose\n"
 USAGE="$USAGE \n"
 USAGE="$USAGE Example:\n"
-USAGE="$USAGE \t paw_do -f \n"
+USAGE="$USAGE \t paw_do -F \n"
 USAGE="$USAGE \n"
 #-------------------------------------------------------------------------------
 #  individual data
@@ -108,7 +110,7 @@ function findroot(){
 #-------------------------------------------------------------------------------
 #  resolve argument list
 #-------------------------------------------------------------------------------
-OPTSTRING=":hv0afsdwtz"
+OPTSTRING=":hv0AFPSDWTZ"
 OPTIND=0
 while getopts "${OPTSTRING}" OPT  ; do
   case $OPT in
@@ -148,7 +150,7 @@ fi
 OPTIND=0  # reset argument position
 while getopts "${OPTSTRING}" OPT  ; do
  case $OPT in
-    a) # paw_show -ce $ROOT
+    A) # paw_show -ce $ROOT
       Y=$(findroot prot)
       Y=${Y%.prot}
       if [[ -n $Y ]] ; then      
@@ -159,7 +161,7 @@ while getopts "${OPTSTRING}" OPT  ; do
         exit 1
       fi
       ;;
-    d) # paw_dos.x $ROOT.dcntl
+    D) # paw_dos.x $ROOT.dcntl
       Y=$(findroot dcntl)
       if [[ -n $Y ]] ; then      
         execute "paw_dos.x  $Y"
@@ -175,7 +177,7 @@ while getopts "${OPTSTRING}" OPT  ; do
         execute "xmgrace -free -noask -batch $Y.bat"
       fi
       ;;
-    f) # paw_fast.x $ROOT.cntl
+    F) # paw_fast.x $ROOT.cntl
       Y=$(findroot cntl)
       if [[ -n $Y ]] ; then      
         execute "paw_fast.x  $Y 1>out 2>&1 &"
@@ -186,7 +188,19 @@ while getopts "${OPTSTRING}" OPT  ; do
         exit 1
       fi
       ;;
-    s) # paw_strc.x -c 
+    P) # ppaw_fast.x $ROOT.cntl 
+      Y=$(findroot cntl)
+      Y=${Y%.cntl}
+      if [[ -n $Y ]] ; then      
+        execute "doppaw $Y 4 &"
+        execute "tail -f ${Y%.cntl}.prot"
+       else
+        echo "error in $0 for option $OPT" >&2
+        echo "*.cntl file not unique or not present" >&2
+        exit 1
+      fi
+      ;;
+    S) # paw_strc.x -c 
       Y=$(findroot strc_out)
       Y=${Y%.strc_out}
       if [[ -n $Y ]] ; then      
@@ -197,7 +211,7 @@ while getopts "${OPTSTRING}" OPT  ; do
         exit 1
       fi
       ;;
-    w) # paw_wave.x $ROOT.wcntl
+    W) # paw_wave.x $ROOT.wcntl
       Y=$(findroot wcntl)
       if [[ -n $Y ]] ; then      
         execute "paw_wave.x  $Y"
@@ -207,7 +221,7 @@ while getopts "${OPTSTRING}" OPT  ; do
         exit 1
       fi
       ;;
-    t) # paw_tra.x $ROOT.tcntl
+    T) # paw_tra.x $ROOT.tcntl
       Y=$(findroot tcntl)
       if [[ -n $Y ]] ; then      
         execute "paw_tra.x  $Y"
@@ -217,7 +231,7 @@ while getopts "${OPTSTRING}" OPT  ; do
         exit 1
       fi
       ;;
-    z) # tail -f $ROOT.prot
+    Z) # tail -f $ROOT.prot
       Y=$(findroot prot)
       if [[ -n $Y ]] ; then      
         execute "tail -f $Y"
