r759 | ptpb | 2007-06-28 11:23:32 +0200 (Do, 28. Jun 2007) | 3 Zeilen Geänderte Pfade:    M /branches/pbloechl/main/Makefile_bare.in    M /branches/pbloechl/main/configure    M /branches/pbloechl/main/configure.ac    M /branches/pbloechl/main/src/Docs/history.tex    M /branches/pbloechl/main/src/Tools/Atomnew/paw_newatom.f90    M /branches/pbloechl/main/src/paw.f90    M /branches/pbloechl/main/src/paw_atoms.f90    M /branches/pbloechl/main/src/paw_brillouin.f90    M /branches/pbloechl/main/src/paw_constants.f90    M /branches/pbloechl/main/src/paw_cosmo.f90    M /branches/pbloechl/main/src/paw_dimer.f90    M /branches/pbloechl/main/src/paw_forcefield.f90    M /branches/pbloechl/main/src/paw_ionew.f90    M /branches/pbloechl/main/src/paw_mpelib.f90    M /branches/pbloechl/main/src/paw_occupations.f90    M /branches/pbloechl/main/src/paw_qmmm.f90    M /branches/pbloechl/main/src/paw_schroedinger.f90    M /branches/pbloechl/main/src/paw_setupread.f90    M /branches/pbloechl/main/src/paw_setups.f90    M /branches/pbloechl/main/src/paw_waves1.f90    M /branches/pbloechl/main/src/paw_waves2.f90
Bugfix for parallelization in paw_waves2.f90, in waves_read
Small changes in paw_newatom

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1690,6 +1690,42 @@ else
   PARMFILE=notset
 fi
 
+if test "$PARMFILE" = "notset"; then
+ { { echo "$as_me:$LINENO: error: parmfile must be specified: use option --with-parmfile=parmfile" >&5
+echo "$as_me: error: parmfile must be specified: use option --with-parmfile=parmfile" >&2;}
+   { (exit 1); exit 1; }; }
+else
+ as_ac_File=`echo "ac_cv_file_$PARMFILE" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for $PARMFILE" >&5
+echo $ECHO_N "checking for $PARMFILE... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$PARMFILE"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  TCHK="T"
+else
+  TCHK="F"
+fi
+
+ if test "$TCHK" = "F"; then
+   { { echo "$as_me:$LINENO: error: parmfile $PARMFILE not found" >&5
+echo "$as_me: error: parmfile $PARMFILE not found" >&2;}
+   { (exit 1); exit 1; }; }
+ fi
+fi
 #
 # Check for GNU make utility
 #
