small bugfixes, cleanup and reduce output from make

diff --git a/paw_install b/paw_install
--- a/paw_install
+++ b/paw_install
@@ -1,5 +1,8 @@
 #!/bin/bash
 export THISDIR=$(pwd)
+export RC1=0
+export RC2=0
+export RC3=0
 #
 #-------------------------------------------------------------------------------
 #--  install cp-paw package                                                   --
@@ -17,12 +20,23 @@ export THISDIR=$(pwd)
 #  
 #-------------------------------------------------------------------------------
 echo "======================== building dbg  =================================="
-src/Buildtools/paw_build.sh -v -j10 -c dbg               1>out_dbg 2>&1 &
+src/Buildtools/paw_build.sh -v -j10 -c dbg           \
+                            1>out_dbg 2>&1 ; RC1=$? &
 echo "======================== building fast==================================="
-src/Buildtools/paw_build.sh -v -j10 -c fast -z           1>out_fast 2>&1 &
+src/Buildtools/paw_build.sh -v -j10 -c fast -z   \
+                            1>out_fast 2>&1 ; RC2=$? &
 echo "======================== building fast_parallel ========================="
-src/Buildtools/paw_build.sh -v -j10 -c fast_parallel -z  1>out_fastp 2>&1 &
+src/Buildtools/paw_build.sh -v -j10 -c fast_parallel -z  \
+                            1>out_fastp 2>&1 ; RC3=$? &
 wait
+if [[ $RC1 != 0 || $RC2 != 0 || $RC3 != 0 ]] ; then
+  echo "-------------------------------------------------------------------" >&2
+  echo "error in $0: installation failed " >&2
+  echo "RC1=$RC1, RC2=$RC2, RC2=$RC3"      >&2
+  echo "shutting down $0"                  >&2
+  echo "-------------------------------------------------------------------" >&2
+  exit 1
+fi
 #
 #
 echo " "
