Add cuFFTW profiling build profiles

diff --git a/paw_install b/paw_install
--- a/paw_install
+++ b/paw_install
@@ -19,8 +19,10 @@ export THISDIR=$(pwd)
 export NODOC=""  # suppress building documentation except once
 export CPPAW_INSTALL_NVHPC="${CPPAW_INSTALL_NVHPC:-auto}"
 export CPPAW_INSTALL_NVBLAS="${CPPAW_INSTALL_NVBLAS:-auto}"
+export CPPAW_INSTALL_CUFFTW="${CPPAW_INSTALL_CUFFTW:-auto}"
 export CPPAW_INSTALL_CUBLAS_ACC="${CPPAW_INSTALL_CUBLAS_ACC:-auto}"
 export CPPAW_INSTALL_PROFILE="${CPPAW_INSTALL_PROFILE:-no}"
+export CPPAW_INSTALL_JOBS="${CPPAW_INSTALL_JOBS:-16}"
 
 function has_cuda {
   if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1 ; then
@@ -55,6 +57,15 @@ function has_nvblas {
   return 1
 }
 
+function has_cufftw {
+  local X
+  for X in /opt/nvidia/hpc_sdk/Linux_*/*/math_libs/*/targets/*/lib \
+           /opt/nvidia/hpc_sdk/Linux_*/*/math_libs/*/lib64 ; do
+    if [[ -f ${X}/libcufftw.so && -f ${X}/libcufft.so ]] ; then return 0 ; fi
+  done
+  return 1
+}
+
 function build_choice {
   local CHOICE=$1
   local REQUIRED=$2
@@ -64,9 +75,9 @@ function build_choice {
   echo "======================== building ${CHOICE}  ================================="
   if [[ -n ${TOOLCHAIN} ]] ; then
     CPPAW_TOOLCHAIN=${TOOLCHAIN} src/Buildtools/paw_build.sh \
-      -v -j10 -c ${CHOICE} ${NODOC} 1>out_${CHOICE} 2>err_${CHOICE}
+      -v -j"${CPPAW_INSTALL_JOBS}" -c ${CHOICE} ${NODOC} 1>out_${CHOICE} 2>err_${CHOICE}
   else
-    src/Buildtools/paw_build.sh -v -j10 -c ${CHOICE} ${NODOC} \
+    src/Buildtools/paw_build.sh -v -j"${CPPAW_INSTALL_JOBS}" -c ${CHOICE} ${NODOC} \
       1>out_${CHOICE} 2>err_${CHOICE}
   fi
   export RC=$?
@@ -120,6 +131,8 @@ export NVHPC_BUILT=false
 export NVHPC_PROFILE_BUILT=false
 export NVBLAS_BUILT=false
 export NVBLAS_PROFILE_BUILT=false
+export CUFFTW_BUILT=false
+export CUFFTW_PROFILE_BUILT=false
 export CUBLAS_ACC_BUILT=false
 export CUBLAS_ACC_PROFILE_BUILT=false
 
@@ -217,11 +230,60 @@ function build_cublas_acc_choices {
   fi
 }
 
+function build_cufftw_choices {
+  local REQUIRED=$1
+
+  case "${CPPAW_INSTALL_CUFFTW}" in
+    no|false|0)
+      return 0
+      ;;
+    auto|"")
+      if ! has_cuda || ! has_cufftw ; then
+        echo "CUDA/cuFFTW not detected; skipping optional nvhpc_cufftw builds."
+        return 0
+      fi
+      ;;
+    require|required|yes|true)
+      if ! has_cuda || ! has_cufftw ; then
+        echo "error in $0: CPPAW_INSTALL_CUFFTW=${CPPAW_INSTALL_CUFFTW} but CUDA/cuFFTW was not found" >&2
+        exit 1
+      fi
+      REQUIRED=true
+      ;;
+    *)
+      echo "error in $0: invalid CPPAW_INSTALL_CUFFTW=${CPPAW_INSTALL_CUFFTW}" >&2
+      echo "allowed are auto, no, require" >&2
+      exit 1
+      ;;
+  esac
+
+  for X in nvhpc_cufftw_fast nvhpc_cufftw_fast_parallel ; do
+    build_choice "${X}" "${REQUIRED}" "nvhpc"
+    if [[ ${LAST_BUILD_OK} = true ]] ; then
+      CUFFTW_BUILT=true
+    fi
+  done
+  if profile_requested ; then
+    for X in nvhpc_cufftw_profile nvhpc_cufftw_profile_parallel ; do
+      build_choice "${X}" "${REQUIRED}" "nvhpc"
+      if [[ ${LAST_BUILD_OK} = true ]] ; then
+        CUFFTW_PROFILE_BUILT=true
+      fi
+    done
+  fi
+}
+
 case "${CPPAW_INSTALL_NVHPC}" in
   no|false|0)
     case "${CPPAW_INSTALL_NVBLAS}" in
       require|required|yes|true)
         echo "error in $0: CPPAW_INSTALL_NVBLAS=${CPPAW_INSTALL_NVBLAS} but CPPAW_INSTALL_NVHPC=${CPPAW_INSTALL_NVHPC}" >&2
+        exit 1
+        ;;
+    esac
+    case "${CPPAW_INSTALL_CUFFTW}" in
+      require|required|yes|true)
+        echo "error in $0: CPPAW_INSTALL_CUFFTW=${CPPAW_INSTALL_CUFFTW} but CPPAW_INSTALL_NVHPC=${CPPAW_INSTALL_NVHPC}" >&2
         exit 1
         ;;
     esac
@@ -248,6 +310,7 @@ case "${CPPAW_INSTALL_NVHPC}" in
       done
     fi
     build_nvblas_choices false
+    build_cufftw_choices false
     build_cublas_acc_choices false
     ;;
   auto|"")
@@ -267,6 +330,7 @@ case "${CPPAW_INSTALL_NVHPC}" in
         done
       fi
       build_nvblas_choices false
+      build_cufftw_choices false
       build_cublas_acc_choices false
     else
       case "${CPPAW_INSTALL_NVBLAS}" in
@@ -276,6 +340,12 @@ case "${CPPAW_INSTALL_NVHPC}" in
           ;;
         *)
           echo "NVIDIA HPC SDK/CUDA not detected; skipping optional nvhpc builds."
+          ;;
+      esac
+      case "${CPPAW_INSTALL_CUFFTW}" in
+        require|required|yes|true)
+          echo "error in $0: CPPAW_INSTALL_CUFFTW=${CPPAW_INSTALL_CUFFTW} but NVIDIA HPC SDK/CUDA was not found" >&2
+          exit 1
           ;;
       esac
       case "${CPPAW_INSTALL_CUBLAS_ACC}" in
@@ -316,6 +386,12 @@ if [[ ${NVBLAS_BUILT} = true ]] ; then
 fi
 if [[ ${NVBLAS_PROFILE_BUILT} = true ]] ; then
   echo "export PATH=\${PAWDIR}/bin/nvhpc_nvblas_profile:\${PAWDIR}/bin/nvhpc_nvblas_profile_parallel:\${PATH}"
+fi
+if [[ ${CUFFTW_BUILT} = true ]] ; then
+  echo "export PATH=\${PAWDIR}/bin/nvhpc_cufftw_fast:\${PAWDIR}/bin/nvhpc_cufftw_fast_parallel:\${PATH}"
+fi
+if [[ ${CUFFTW_PROFILE_BUILT} = true ]] ; then
+  echo "export PATH=\${PAWDIR}/bin/nvhpc_cufftw_profile:\${PAWDIR}/bin/nvhpc_cufftw_profile_parallel:\${PATH}"
 fi
 if [[ ${CUBLAS_ACC_BUILT} = true ]] ; then
   echo "export PATH=\${PAWDIR}/bin/nvhpc_cublas_acc_fast:\${PAWDIR}/bin/nvhpc_cublas_acc_fast_parallel:\${PATH}"
diff --git a/src/Buildtools/defaultparmfile b/src/Buildtools/defaultparmfile
--- a/src/Buildtools/defaultparmfile
+++ b/src/Buildtools/defaultparmfile
@@ -78,6 +78,7 @@ export CPPAW_CUDA_AVAILABLE=false
 export CPPAW_CUDA_ROOT=
 export CPPAW_CUDA_CC=
 export CPPAW_USE_NVBLAS="${CPPAW_USE_NVBLAS:-no}"
+export CPPAW_USE_CUFFTW="${CPPAW_USE_CUFFTW:-no}"
 export CPPAW_USE_CUBLAS_ACC="${CPPAW_USE_CUBLAS_ACC:-no}"
 
 ################################################################################
@@ -187,6 +188,29 @@ function find_nvhpc_nvblas_libdir {
   done
 }
 
+function find_nvhpc_cufft_libdir {
+  local D
+  for D in "${NVHPC_ROOT}"/math_libs/*/targets/*/lib \
+           "${NVHPC_ROOT}"/math_libs/*/lib64 \
+           "${NVHPC_ROOT}"/math_libs/*/lib ; do
+    if [[ -f ${D}/libcufftw.so && -f ${D}/libcufft.so ]] ; then
+      echo "${D}"
+      return 0
+    fi
+  done
+}
+
+function find_nvhpc_fftw3_include {
+  local D
+  for D in "${NVHPC_ROOT}"/compilers/include/nvpl_fftw/fftw3.f03 \
+           "${NVHPC_ROOT}"/math_libs/nvpl/include/nvpl_fftw/fftw3.f03 ; do
+    if [[ -f ${D} ]] ; then
+      echo "${D}"
+      return 0
+    fi
+  done
+}
+
 function fortran_module_works {
   local MODULE=$1
   local CFLAGS=$2
@@ -246,6 +270,9 @@ case "${SELECT}" in
 esac
 case "${SELECT}" in
   nvhpc_nvblas*) CPPAW_USE_NVBLAS=yes ;;
+esac
+case "${SELECT}" in
+  nvhpc_cufftw*) CPPAW_USE_CUFFTW=yes ;;
 esac
 case "${SELECT}" in
   nvhpc_cublas_acc*) CPPAW_USE_CUBLAS_ACC=yes ;;
@@ -376,6 +403,8 @@ fi
 
 if [[ ${COMPILER} = nvfortran && -n ${NVHPC_ROOT} ]] ; then
   NVPL_ROOT="${NVHPC_ROOT}/math_libs/nvpl"
+  CUFFTW_LIBDIR=$(find_nvhpc_cufft_libdir)
+  FFTW3_INCLUDE=$(find_nvhpc_fftw3_include)
   if [[ -f ${NVPL_ROOT}/include/nvpl_fftw/fftw3.f03 \
         && -f ${NVPL_ROOT}/lib/libnvpl_fftw.so ]] ; then
     FCFLAGS="${FCFLAGS} -I${NVPL_ROOT}/include -I${NVPL_ROOT}/include/nvpl_fftw"
@@ -393,15 +422,56 @@ if [[ ${COMPILER} = nvfortran && -n ${NVHPC_ROOT} ]] ; then
       LIBS="${LIBS} -L${NVPL_ROOT}/lib"
       LIBS="${LIBS} -lnvpl_lapack_lp64_seq -lnvpl_lapack_core"
       LIBS="${LIBS} -lnvpl_blas_lp64_seq -lnvpl_blas_core -lnvpl_fftw"
+    elif [[ ${CPPAW_USE_CUFFTW} = yes \
+            || ${CPPAW_USE_CUFFTW} = true \
+            || ${CPPAW_USE_CUFFTW} = 1 ]] ; then
+      if [[ ${CPPAW_CUDA_AVAILABLE} != true || -z ${CUFFTW_LIBDIR} ]] ; then
+        echo "error in $0: cuFFTW requested but CUDA/cuFFTW was not found"
+        exit 1
+      fi
+      if [[ -z ${FFTW3_INCLUDE} ]] ; then
+        echo "error in $0: cuFFTW requested but fftw3.f03 was not found"
+        exit 1
+      fi
+      LDFLAGS="${LDFLAGS} -L${CUFFTW_LIBDIR} -Wl,-rpath,${CUFFTW_LIBDIR}"
+      LDFLAGS="${LDFLAGS} -L${NVPL_ROOT}/lib -Wl,-rpath,${NVPL_ROOT}/lib"
+      LIBS="${LIBS} -L${NVPL_ROOT}/lib"
+      LIBS="${LIBS} -lnvpl_lapack_lp64_seq -lnvpl_lapack_core"
+      LIBS="${LIBS} -lnvpl_blas_lp64_seq -lnvpl_blas_core"
+      LIBS="${LIBS} -L${CUFFTW_LIBDIR} -lcufftw -lcufft"
+      INCLUDES="${INCLUDES} ${FFTW3_INCLUDE}"
+      CPPFLAGS="${CPPFLAGS} -DCPPVAR_CUFFTW"
     else
       LDFLAGS="${LDFLAGS} -L${NVPL_ROOT}/lib -Wl,-rpath,${NVPL_ROOT}/lib -Mnvpl=blas,lapack,fft"
       LIBS="${LIBS} -L${NVPL_ROOT}/lib -lnvpl_fftw"
+      INCLUDES="${INCLUDES} ${NVPL_ROOT}/include/nvpl_fftw/fftw3.f03"
     fi
-    INCLUDES="${INCLUDES} ${NVPL_ROOT}/include/nvpl_fftw/fftw3.f03"
     LIB_BLAS_OK="yes"
     LIB_LAPACK_OK="yes"
     LIB_FFTW3_OK="yes"
   fi
+fi
+
+if [[ ${COMPILER} = nvfortran \
+      && ( ${CPPAW_USE_CUFFTW} = yes \
+           || ${CPPAW_USE_CUFFTW} = true \
+           || ${CPPAW_USE_CUFFTW} = 1 ) \
+      && -z ${LIB_FFTW3_OK} ]] ; then
+  CUFFTW_LIBDIR=$(find_nvhpc_cufft_libdir)
+  FFTW3_INCLUDE=$(find_nvhpc_fftw3_include)
+  if [[ ${CPPAW_CUDA_AVAILABLE} != true || -z ${CUFFTW_LIBDIR} ]] ; then
+    echo "error in $0: cuFFTW requested but CUDA/cuFFTW was not found"
+    exit 1
+  fi
+  if [[ -z ${FFTW3_INCLUDE} ]] ; then
+    echo "error in $0: cuFFTW requested but fftw3.f03 was not found"
+    exit 1
+  fi
+  LDFLAGS="${LDFLAGS} -L${CUFFTW_LIBDIR} -Wl,-rpath,${CUFFTW_LIBDIR}"
+  LIBS="${LIBS} -L${CUFFTW_LIBDIR} -lcufftw -lcufft"
+  INCLUDES="${INCLUDES} ${FFTW3_INCLUDE}"
+  CPPFLAGS="${CPPFLAGS} -DCPPVAR_CUFFTW"
+  LIB_FFTW3_OK="yes"
 fi
 
 function enable_nvhpc_cublas_acc {
@@ -630,6 +700,32 @@ case ${SELECT} in
 
   nvhpc_nvblas_profile_parallel)
     SUFFIX="nvhpc_nvblas_profile"
+    TYPE="profile"
+    CPPFLAGS="${CPPFLAGS} -DCPPVAR_ACCEL_PROFILE"
+    add_fcflags
+    ;;
+
+  nvhpc_cufftw_fast)
+    SUFFIX="nvhpc_cufftw_fast"
+    TYPE="release"
+    add_fcflags
+    ;;
+
+  nvhpc_cufftw_fast_parallel)
+    SUFFIX="nvhpc_cufftw_fast"
+    TYPE="release"
+    add_fcflags
+    ;;
+
+  nvhpc_cufftw_profile)
+    SUFFIX="nvhpc_cufftw_profile"
+    TYPE="profile"
+    CPPFLAGS="${CPPFLAGS} -DCPPVAR_ACCEL_PROFILE"
+    add_fcflags
+    ;;
+
+  nvhpc_cufftw_profile_parallel)
+    SUFFIX="nvhpc_cufftw_profile"
     TYPE="profile"
     CPPFLAGS="${CPPFLAGS} -DCPPVAR_ACCEL_PROFILE"
     add_fcflags
