adjust makefiles to new f90pp

diff --git a/src/Buildtools/F90PP/f90pp.in b/src/Buildtools/F90PP/f90pp.in
--- a/src/Buildtools/F90PP/f90pp.in
+++ b/src/Buildtools/F90PP/f90pp.in
@@ -1,45 +1,4 @@
 #!/bin/bash
-set +x
-########################################################################
-###                                                                   ##
-###  name: f90pp                                                      ##
-###                                                        	      ##
-###  f90pp options rawsourcefile > processedsourcefile                ##
-###                                                        	      ##
-###  options                                               	      ##
-###    -Dname                                              	      ##
-###       directive for the cpp preprocessor               	      ##
-###    -notemplates                                        	      ##
-###       use this option to compile f90pp_templates.f90   	      ##
-###       used by f90pp. templates are not expanded        	      ##
-###                                                        	      ##
-###  purpose: fortran90 preprocessor                       	      ##
-###    1) expands templates                                	      ##
-###    2) replaces dollar signs in subroutine names        	      ##
-###       to conform with fortran90 standard               	      ##
-###    3) remove xlf compiler options when required        	      ##
-###    4) lowercase cpp directives                         	      ##
-###    5) run c-preprocessor cpp                           	      ##
-###                                                        	      ##
-###  preprocessor directives                                  	      ##
-###    -DCPPVARIABLE_PARALLEL   !parallel/scalar paw_mpelib   	      ##
-###    -DCPPVAR_SUPPORT_XLF                                    	      ##
-###    -DCPPVAR_XLFWORKAROUND                                         ##
-###    -DCPPVAR_USAGE_EXIST                                   	      ##
-###    -DCPPVAR_LANGEXT_XLF                                   	      ##
-###    -DCPPVAR_BLAS_ESSL                                     	      ##
-###    -DCPPVAR_FFT_ESSL                                       	      ##
-###    -DCPPVAR_FFT_PACK                                       	      ##
-###    -DCPPVAR_FFT_FFTW                                     	      ##
-###    -DCPPVAR_U77                                            	      ##
-###    -DCPPVAR_BLAS_ATLAS       !not used                            ##
-###    -DCPPVAR_FFT_PACK         !not used                            ##
-###    -DCPPVAR_FFT_CXML         !not used                            ##
-###    -DCPPVARIABLE_DEC         !not used                            ##
-###    -DCPPVAR_BLAS_EXPLICIT    !not used                            ##
-###    -DCPPVARIABLE_ABS         !not used                    	      ##
-###                                                        	      ##
-########################################################################
 #
 # The following block of variables is defined by the
 # configure script
@@ -47,105 +6,77 @@ set +x
 #______________________ 
 THISDIR="@THISDIR@"
 #______________________ 
-CPP="@CPP@"
+CPP="@CPP@ "
 #______________________ 
 ARCH="@ARCH@"
 #______________________ 
-SPECIAL="@SPECIAL@"
+#SPECIAL="@SPECIAL@"
 #
-########################################################################
-##                                                                    ##
-##  define derived variables                                          ##
-##                                                                    ##
-########################################################################
-#______________________________location of f90pp source files
-F90PPDIR=${THISDIR}/src/Buildtools/F90PP
-#______________________________final location of the f90pp preprocessor
-BINDIR=${THISDIR}/bin/$ARCH
-#
-if test "${SPECIAL}" = "IBM" ; then
-  POE_PREFIX='poe'
-  POE_SUFFIX='-proc 1 -nodes 1 -rmpool 0'
-else
-  POE_PREFIX=
-  POE_SUFFIX=
-fi
-#
-########################################################################
-##                                                                    ##
-##  resolve command line arguments                                    ##
-##                                                                    ##
-########################################################################
-OPTIONS=$@
-TEMPLATES=T
-CPPVAR=""
-for i in $OPTIONS; do
-  case $i in
-    -D*)                    # variables for c-preprocessor 
-     CPPVAR="$CPPVAR $1"
-     shift
-    ;;
-    -notemplates)           # use this option to transform f90pp_tmplts.f
-     TEMPLATES="F"
-     shift
-     ;;
-   -*)                      # unknown options
-    echo "\n unknown option $1 in f90pp"
-    exit 1
-    ;;
-   *)
-    ARG=$1                  # last argument is name of the source file
-    break
-    ;;
+#-------------------------------------------------------------------------------
+# export THISDIR=$(pwd)
+# export ARCH='osx_gfortran_accellerate'
+
+export BINDIR=${THISDIR}/bin/$ARCH
+export F90PPDIR=${THISDIR}/src/Buildtools/F90PP
+#BINDIR="./"
+#F90PPDIR="./"
+
+#----------------------------------------------------------------
+#  help message
+#----------------------------------------------------------------
+export USAGE="\n"
+USAGE="$USAGE Usage of $0:\n"
+USAGE="$USAGE \t f90pp options <infile >outfile\n"
+USAGE="$USAGE fortran preprocessor for cppaw\n"
+USAGE="$USAGE Options \n"
+USAGE="$USAGE \t -D c-preprocessor directive\n"
+#USAGE="$USAGE \t -v verbose\n"
+USAGE="$USAGE \t -h prints this help message\n"
+
+#----------------------------------------------------------------
+#  Resolve arguments
+#----------------------------------------------------------------
+while getopts :hD: OPT ; do
+  case $OPT in
+    D) CPPVAR="$CPPVAR -D$OPTARG" ;;
+#    v) VERBOSE="Y" ;;
+    h) echo -e $USAGE ; exit 0  ;;
+    \?)   # unknown option (placed into OPTARG, if OPTSTRING starts with :)
+      echo "error in $0" >&2
+      echo "invalid option -$OPTARG" >&2
+      echo "retrieve argument list with:" >&2
+      echo "$0 -h" >&2
+      exit 1
+      ;;
+    :)    # no argument passed
+      ;;
   esac
 done
-#
-########################################################################
-##                                                                    ##
-##  define transformations DO1,DO2,DO3,DO4 of the source file         ##
-##                                                                    ##
-########################################################################
-# expand templates
-DO1="${BINDIR}/f90pp_tmplts.x"
-if test "$TEMPLATES" = "F" ; then
-  DO1="cat"
-fi
-#
-# remove xlf compiler directives
-# sed /^@/d removes all lines beginning with @
-DO2="sed /^@/d"
-#
-# make directives for the c-preprocessor lowercase
-DO3="sed -f ${F90PPDIR}/f90pp.sed"
-#
-# define the c-processor                                              ==
-# -C does not remove C-comment lines (starting //)
-# -P Preprocesses input without producing line control information for the next pass of the C compiler.
-# -DName[=Definition] Defines Name as in a #define directive. The default Definition is 1.
-DO4="$CPP -P -C -nostdinc $CPPVAR"
-#
-#  take care of special rules
-#
-if test "${SPECIAL}" = "IBM" ; then
-  # leave xlf compiler directives intact
-  DO2="cat" 
-  if test "$DO1" != "cat" ; then
-    DO1="${POE_PREFIX} $DO1 ${POE_SUFFIX}"
+
+#----------------------------------------------------------------
+#  compile f90_tmplts.f90
+#----------------------------------------------------------------
+# generate executable F90TMPLTS_X if unavailable.
+# regenerate if executable is older than source
+F90TMPLTS_X="${BINDIR}/f90pp_tmplts.x"
+if [[ -f $F90TMPLTS_X ]] ; then
+  if [[ $F90TMPLTS_X -ot $F90PPDIR/f90pp_tmplts.f90 ]] ; then
+    rm $F90TMPLTS_X
   fi
 fi
-#
-########################################################################
-##                                                                    ##
-##  transform source file and send result to standard out             ##
-##                                                                    ##
-########################################################################
-${DO1} < $ARG | $DO2 | $DO3 | $DO4 
-RC=$?
-if [[ $RC != 0 ]] ; then 
-  echo "error in $0: last command failed with RC=$RC"
-  echo "try to  execute ulimit -s unlimited"
-  exit 2
-fi              
-exit 0
+if [[ ! -e $F90TMPLTS_X ]] ; then
+ echo 'rebuilding $F90TMPLTS_X'
+  TMP=$(mktemp).f90 
+  sed 's/[$]/__/g' $F90PPDIR/f90pp_tmplts.f90 > $TMP 
+  export MODDIR=$(mktemp -d)
+  gfortran -I${MODDIR} -J${MODDIR} -o $F90TMPLTS_X $TMP
+  rm $TMP
+fi 
 
-
+#----------------------------------------------------------------
+# convert source code
+#----------------------------------------------------------------
+${F90TMPLTS_X} < /dev/stdin |\
+sed -f "${F90PPDIR}/f90pp.sed"  |\
+sed /^@/d  |\
+$CPP -traditional -P -C -nostdinc $CPPVAR >/dev/stdout
