new installation procedure

diff --git a/src/Buildtools/F90PP/f90pp.in b/src/Buildtools/F90PP/f90pp.in
--- a/src/Buildtools/F90PP/f90pp.in
+++ b/src/Buildtools/F90PP/f90pp.in
@@ -1,29 +1,23 @@
 #!/bin/bash
-#
-# The following block of variables is defined by the
-# configure script
-#
-#______________________ 
-THISDIR="@THISDIR@"
-#______________________ 
-CPP="@CPP@ "
-#______________________ 
-ARCH="@ARCH@"
-#________________________
-COMPILE="@COMPILE_SCALAR@"
-#
-export BINDIR=${THISDIR}/bin/${ARCH}
-export F90PPDIR=${THISDIR}/src/Buildtools/F90PP
-# #-----------------------------------------------------------------------------
-export F90TMPLTS_X="${BINDIR}/f90pp_tmplts.x"
-if [[ ! -e ${F90PPDIR}/f90pp.sed ]] ; then
-  echo "error in $0: $F90PPDIR/f90.sed not found"
-  exit 1
-fi
-#
-#----------------------------------------------------------------
+#________1_________2_________3_________4_________5_________6_________7_________8
+################################################################################
+##                                                                            ##
+## f90pp                                                                      ##
+##                                                                            ##
+##    -- replaces dollar signs by double underscore (fdollar_ok.sh)           ##
+##    -- removes directives (lines starting with @)                           ##
+##    -- applies c-preprocessor (input option -D)                             ##
+##    -- resolves templates (f90pp_tmplts.x)                                  ##
+##    -- replacements with f90pp.sed                                          ##
+##                                                                            ##
+## requirements:                                                              ##
+##    etc/f90pp.tmplts.x, etc/f90pp.sed, etc/fdollar_ok.sh                    ##
+##                                                                            ##
+##                                                                            ##
+################################################################################
+#-------------------------------------------------------------------------------
 #  help message
-#----------------------------------------------------------------
+#-------------------------------------------------------------------------------
 export USAGE="\n"
 USAGE="$USAGE Usage of $0:\n"
 USAGE="$USAGE \t f90pp options <infile >outfile\n"
@@ -32,17 +26,10 @@ USAGE="$USAGE Options \n"
 USAGE="$USAGE \t -D c-preprocessor directive\n"
 #USAGE="$USAGE \t -v verbose\n"
 USAGE="$USAGE \t -h prints this help message\n"
-#
-#----------------------------------------------------------------
-#  compile F90TMPLTS  if not available
-#----------------------------------------------------------------
-if [[ ! -e ${F90TMPLTS_X} ]] ; then
-  sed -e "s/[$]/__/" < ${F90PPDIR}/f90pp_tmplts.f90 |\
-  ${COMPILE} -o${F90TMPLTS_X} 
-fi
-#----------------------------------------------------------------
+
+#-------------------------------------------------------------------------------
 #  Resolve arguments
-#----------------------------------------------------------------
+#-------------------------------------------------------------------------------
 while getopts :hD: OPT ; do
   case $OPT in
     D) CPPVAR="$CPPVAR -D$OPTARG" ;;
@@ -59,10 +46,66 @@ while getopts :hD: OPT ; do
       ;;
   esac
 done
-#----------------------------------------------------------------
+
+#___the variable @CPP@ can be replaced \
+#___by sed -s/@CPP@/${CPP}/g f90pp.in > f9ppp
+CPP=@CPP@
+if [[ ! -x $CPP ]] ; then
+   CPP=$(which cpp)
+fi
+
+#-------------------------------------------------------------------------------
+#  compile F90TMPLTS  if not available
+#-------------------------------------------------------------------------------
+# if [[ -e etc/f90pp_tmplts.x ]] ; then
+#   if [[ etc/f90pp_tmplts.x -ot ${F90PPDIR}/f90pp_tmplts.f90 ]] ; then
+#     rm etc/f90pp_tmplts.x
+#   fi
+# fi
+# if [[ ! -e etc/f90pp_tmplts.x ]] ; then
+#   TMP=$(mktemp).f90
+#   sed -e "s/[$]/__/" < ${F90PPDIR}/f90pp_tmplts.f90 >$TMP
+#   ${COMPILE} -oetc/f90pp_tmplts.x $TMP
+#   rm -f $TMP
+# fi
+
+
+#-------------------------------------------------------------------------------
+#  Checks
+#-------------------------------------------------------------------------------
+if [[ ! -f etc/f90pp.sed ]] ; then
+  echo "error in $0: etc/f90.sed not found"
+  exit 1
+fi
+if [[ ! -x etc/f90pp_tmplts.x ]] ; then
+  echo "error in $0: etc/f90pp_tmplts.x not found or not executable"
+  exit 1
+fi
+if [[ ! -x etc/dollar_ok.sh ]] ; then
+  if [[ -f etc/dollar_ok.sh ]] ; then
+    echo "error in $0: etc/dollar_ok.sh present but not executable"
+  else
+    echo "error in $0: etc/dollar_ok.sh not found"
+  fi
+  exit 1
+fi
+if [[ ! -x ${CPP} ]] ; then
+  echo "error in $0: c-preprocessor no found"
+  echo "CPP=$CPP"
+  exit 1
+fi
+
+#-------------------------------------------------------------------------------
 # convert source code
-#----------------------------------------------------------------
-${F90TMPLTS_X} < /dev/stdin |\
-sed -f ${F90PPDIR}/f90pp.sed |\
-sed /^@/d  |\
-$CPP  $CPPVAR >/dev/stdout
+#-------------------------------------------------------------------------------
+TMP=$(mktemp)
+TMP2=$(mktemp)
+cat < /dev/stdin > ${TMP2}
+etc/f90pp_tmplts.x < $TMP2 >$TMP
+sed -f etc/f90pp.sed $TMP > $TMP2
+etc/dollar_ok.sh <$TMP2 >$TMP  # convert dollar signs by double underscore
+sed /^@/d  $TMP >$TMP2         # delete lines beginning with @
+${CPP} -P -C $CPPVAR $TMP2 $TMP 
+cat $TMP
+rm -f $TMP
+rm -f $TMP2
