Add Skala grid accelerator profiling support

diff --git a/src/Buildtools/defaultparmfile b/src/Buildtools/defaultparmfile
--- a/src/Buildtools/defaultparmfile
+++ b/src/Buildtools/defaultparmfile
@@ -84,6 +84,7 @@ export CPPAW_USE_CUFFT="${CPPAW_USE_CUFFT:-no}"
 export CPPAW_USE_CUBLAS_ACC="${CPPAW_USE_CUBLAS_ACC:-no}"
 export CPPAW_USE_CUSOLVER_ACC="${CPPAW_USE_CUSOLVER_ACC:-no}"
 export CPPAW_USE_SKALA_FTORCH="${CPPAW_USE_SKALA_FTORCH:-no}"
+export CPPAW_USE_SKALA_GRID_ACC="${CPPAW_USE_SKALA_GRID_ACC:-no}"
 export CPPAW_SKALA_FTORCH_ROOT="${CPPAW_SKALA_FTORCH_ROOT:-}"
 export CPPAW_NVHPC_ACC_FLAGS_ADDED="${CPPAW_NVHPC_ACC_FLAGS_ADDED:-no}"
 export CPPAW_NVHPC_GPU_MEMORY_MODE="${CPPAW_NVHPC_GPU_MEMORY_MODE:-separate}"
@@ -426,6 +427,9 @@ case "${SELECT}" in
 esac
 case "${SELECT}" in
   nvhpc_cusolver_acc*|nvhpc_gpu_acc*|nvhpc_gpu_all*) CPPAW_USE_CUSOLVER_ACC=yes ;;
+esac
+case "${SELECT}" in
+  nvhpc_skala_grid_acc*) CPPAW_USE_SKALA_GRID_ACC=yes ;;
 esac
 
 NVHPC_ROOT=$(find_nvhpc_root)
@@ -778,6 +782,19 @@ function enable_nvhpc_cusolver_acc {
   INCLUDES="${INCLUDES} ${NVHPC_ROOT}/compilers/include/cusolverdn.mod"
   INCLUDES="${INCLUDES} ${NVHPC_ROOT}/compilers/include/cublas_v2.mod"
   INCLUDES="${INCLUDES} ${NVHPC_ROOT}/compilers/include/cudafor.mod"
+  INCLUDES="${INCLUDES} ${NVHPC_ROOT}/compilers/include/openacc.mod"
+}
+
+function enable_nvhpc_skala_grid_acc {
+  if [[ ${CPPAW_CUDA_AVAILABLE} != true ]] ; then
+    echo "error in $0: Skala grid OpenACC target requested but CUDA was not found"
+    exit 1
+  fi
+  if [[ ${COMPILER} != nvfortran ]] ; then
+    echo "error in $0: Skala grid OpenACC target requires nvfortran"
+    exit 1
+  fi
+  append_nvhpc_openacc_flags
   INCLUDES="${INCLUDES} ${NVHPC_ROOT}/compilers/include/openacc.mod"
 }
 
@@ -1215,6 +1232,32 @@ case ${SELECT} in
     add_fcflags
     ;;
 
+  nvhpc_skala_grid_acc_fast)
+    SUFFIX="nvhpc_skala_grid_acc_fast"
+    TYPE="release"
+    add_fcflags
+    ;;
+
+  nvhpc_skala_grid_acc_fast_parallel)
+    SUFFIX="nvhpc_skala_grid_acc_fast"
+    TYPE="release"
+    add_fcflags
+    ;;
+
+  nvhpc_skala_grid_acc_profile)
+    SUFFIX="nvhpc_skala_grid_acc_profile"
+    TYPE="profile"
+    CPPFLAGS="${CPPFLAGS} -DCPPVAR_ACCEL_PROFILE"
+    add_fcflags
+    ;;
+
+  nvhpc_skala_grid_acc_profile_parallel)
+    SUFFIX="nvhpc_skala_grid_acc_profile"
+    TYPE="profile"
+    CPPFLAGS="${CPPFLAGS} -DCPPVAR_ACCEL_PROFILE"
+    add_fcflags
+    ;;
+
   nvhpc_gpu_all_fast)
     SUFFIX="nvhpc_gpu_all_fast"
     TYPE="release"
@@ -1367,6 +1410,12 @@ if [[ ${CPPAW_USE_CUSOLVER_ACC} = yes \
       || ${CPPAW_USE_CUSOLVER_ACC} = true \
       || ${CPPAW_USE_CUSOLVER_ACC} = 1 ]] ; then
   enable_nvhpc_cusolver_acc
+fi
+
+if [[ ${CPPAW_USE_SKALA_GRID_ACC} = yes \
+      || ${CPPAW_USE_SKALA_GRID_ACC} = true \
+      || ${CPPAW_USE_SKALA_GRID_ACC} = 1 ]] ; then
+  enable_nvhpc_skala_grid_acc
 fi
 
 if [[ ${CPPAW_USE_SKALA_FTORCH} = yes \
